'use client';

import React from 'react';
import Link from 'next/link';
import { FileText, ShieldAlert, ArrowLeft, Bot, CheckCircle2, Scale } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="space-y-0 transition-colors duration-300">
      
      {/* Hero Header */}
      <section className="bg-ivory-100 dark:bg-navy-950 py-16 sm:py-24 border-b border-ivory-200 dark:border-navy-900 transition-colors duration-300 relative overflow-hidden">
        <div 
          className="absolute inset-0 opacity-15 dark:opacity-10 pointer-events-none bg-cover bg-center"
          style={{ backgroundImage: "url('/hero-bg.png')" }}
        />
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center space-y-4 relative z-10">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-champagne-100 dark:bg-champagne-500/20 text-champagne-600 dark:text-champagne-400 border border-champagne-200 dark:border-champagne-500/30 text-xs font-bold uppercase tracking-widest">
            <Scale className="w-3.5 h-3.5" />
            <span>Practice Terms & Conditions</span>
          </div>

          <h1 className="font-serif text-4xl sm:text-5xl font-medium tracking-tight text-navy-900 dark:text-ivory-50">
            Terms of Service
          </h1>

          <p className="text-sm text-charcoal-700/80 dark:text-ivory-300/80 max-w-xl mx-auto font-sans leading-relaxed">
            Important terms, practice disclosure agreements, and clinical consultation conditions governing the use of SmileCraft Dental digital platforms.
          </p>

          <div className="text-[11px] font-mono text-charcoal-700/60 dark:text-ivory-400/60 pt-2">
            Last Updated: September 2026 • SmileCraft Dental Practice Compliance
          </div>
        </div>
      </section>

      {/* Main Legal Content Container */}
      <section className="py-16 sm:py-20 bg-ivory-50 dark:bg-navy-900 border-b border-ivory-200 dark:border-navy-800 transition-colors duration-300">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
          
          {/* Demonstration Notice Card */}
          <div className="bg-white dark:bg-navy-950 p-6 rounded-2xl border border-champagne-400/50 dark:border-champagne-500/30 shadow-soft space-y-3">
            <div className="flex items-center gap-2.5 text-champagne-600 dark:text-champagne-400 font-bold text-xs uppercase tracking-wider">
              <ShieldAlert className="w-4 h-4" />
              <span>Demonstration Platform Disclosure</span>
            </div>
            <p className="text-xs text-charcoal-800 dark:text-ivory-200 leading-relaxed font-sans">
              SmileCraft Dental is a fictional luxury dental practice created by <strong>Trishul AI</strong> for sales demonstrations to dental practice leaders. All doctor profiles, location descriptions, technology claims, and scheduling features are designed for interactive evaluation.
            </p>
          </div>

          {/* Terms Articles */}
          <div className="space-y-10 text-charcoal-800 dark:text-ivory-200">
            
            {/* Section 1 */}
            <div className="space-y-3 bg-white dark:bg-navy-950 p-6 sm:p-8 rounded-2xl border border-ivory-200 dark:border-navy-800 shadow-soft">
              <h2 className="font-serif text-2xl font-bold text-navy-900 dark:text-ivory-50 flex items-center gap-2.5">
                <span className="text-champagne-600 dark:text-champagne-400 font-mono text-sm">01.</span>
                Clinical Scope & Medical Disclaimer
              </h2>
              <p className="text-xs sm:text-sm text-charcoal-700/80 dark:text-ivory-300/80 leading-relaxed">
                Information provided on this website, including content generated by the AI Front Desk assistant, is strictly for educational, informational, and scheduling purposes. It does not constitute formal dental diagnosis, emergency medical triage, or clinical advice:
              </p>
              <ul className="space-y-2 text-xs text-charcoal-700/80 dark:text-ivory-300/80 pt-2 font-sans">
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-champagne-500 shrink-0 mt-0.5" />
                  <span>Clinical candidacy for dental implants, veneers, or orthodontic treatment requires an in-person examination.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-champagne-500 shrink-0 mt-0.5" />
                  <span>If you are experiencing severe dental trauma, bleeding, or acute swelling, contact emergency emergency services immediately.</span>
                </li>
              </ul>
            </div>

            {/* Section 2 */}
            <div className="space-y-3 bg-white dark:bg-navy-950 p-6 sm:p-8 rounded-2xl border border-ivory-200 dark:border-navy-800 shadow-soft">
              <h2 className="font-serif text-2xl font-bold text-navy-900 dark:text-ivory-50 flex items-center gap-2.5">
                <span className="text-champagne-600 dark:text-champagne-400 font-mono text-sm">02.</span>
                Appointment Booking & Cancellations
              </h2>
              <p className="text-xs sm:text-sm text-charcoal-700/80 dark:text-ivory-300/80 leading-relaxed">
                When reserving consultation times at our Midtown Manhattan practice, patients are requested to provide at least 24 hours advance notice for cancellations or rescheduling. This allows our clinical staff to accommodate patients needing immediate care.
              </p>
            </div>

            {/* Section 3 */}
            <div className="space-y-3 bg-white dark:bg-navy-950 p-6 sm:p-8 rounded-2xl border border-ivory-200 dark:border-navy-800 shadow-soft">
              <h2 className="font-serif text-2xl font-bold text-navy-900 dark:text-ivory-50 flex items-center gap-2.5">
                <span className="text-champagne-600 dark:text-champagne-400 font-mono text-sm">03.</span>
                AI Front Desk Interaction Terms
              </h2>
              <p className="text-xs sm:text-sm text-charcoal-700/80 dark:text-ivory-300/80 leading-relaxed">
                Interactions with the AI Front Desk receptionist are recorded and transcribed to optimize appointment scheduling efficiency and quality assurance. Patients may request human front-desk staff assistance at any point during telephone calls or digital chats.
              </p>
            </div>

            {/* Section 4 */}
            <div className="space-y-3 bg-white dark:bg-navy-950 p-6 sm:p-8 rounded-2xl border border-ivory-200 dark:border-navy-800 shadow-soft">
              <h2 className="font-serif text-2xl font-bold text-navy-900 dark:text-ivory-50 flex items-center gap-2.5">
                <span className="text-champagne-600 dark:text-champagne-400 font-mono text-sm">04.</span>
                Intellectual Property & Design Rights
              </h2>
              <p className="text-xs sm:text-sm text-charcoal-700/80 dark:text-ivory-300/80 leading-relaxed">
                All branding, tooth logos, custom design tokens, layout code, and Trishul AI front-desk integration concepts displayed on this website are protected under copyright and trademark laws.
              </p>
            </div>

          </div>

          {/* Navigation Action Footer */}
          <div className="pt-6 flex flex-col sm:flex-row items-center justify-between gap-4 border-t border-ivory-200 dark:border-navy-800">
            <Link
              href="/"
              className="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-navy-900 dark:bg-champagne-500 text-ivory-50 dark:text-navy-950 text-xs font-bold hover:bg-navy-800 dark:hover:bg-champagne-400 transition-colors shadow-sm"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Return to Homepage</span>
            </Link>

            <Link
              href="/privacy"
              className="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-white dark:bg-navy-800 text-navy-900 dark:text-ivory-100 border border-ivory-300 dark:border-navy-700 text-xs font-bold hover:bg-ivory-100 dark:hover:bg-navy-700 transition-colors"
            >
              <FileText className="w-4 h-4 text-champagne-600 dark:text-champagne-400" />
              <span>Read Privacy Policy</span>
            </Link>
          </div>

        </div>
      </section>

    </div>
  );
}
